services:
  qortium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${QORTIUM_CONTAINER_NAME:-qortium-core}
    restart: unless-stopped
    expose:
      - "${QORTIUM_API_PORT:-12391}"
      - "${QORTIUM_P2P_PORT:-12392}"
      - "${QORTIUM_QDN_PORT:-12394}"
    volumes:
      - ./data/qortium:/qortium
    networks:
      - qortium_net

networks:
  qortium_net:
    name: ${QORTIUM_NETWORK_NAME:-qortium-net}
    driver: bridge
