services:
  qortium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${QORTIUM_CONTAINER_NAME:-qortium-core}
    restart: unless-stopped
    environment:
      QORTIUM_API_PORT: "${QORTIUM_API_PORT:-24891}"
    expose:
      - "${QORTIUM_API_PORT:-24891}"
      - "${QORTIUM_P2P_PORT:-24892}"
      - "${QORTIUM_QDN_PORT:-24894}"
    volumes:
      - ./data/qortium:/qortium
    networks:
      - qortium_net

networks:
  qortium_net:
    name: ${QORTIUM_NETWORK_NAME:-qortium-net}
    driver: bridge
