rootLogger.level = info

property.logDir = ${sys:qortium.log.dir:-.}

rootLogger.appenderRef.console.ref = stdout
rootLogger.appenderRef.rolling.ref = FILE

logger.bitcoinj.name = org.bitcoinj
logger.bitcoinj.level = error

logger.bcTlsClient.name = org.bouncycastle.jsse.provider.ProvTlsClient
logger.bcTlsClient.level = warn
logger.bcTlsClientProtocol.name = org.bouncycastle.jsse.provider.ProvTlsClientProtocol
logger.bcTlsClientProtocol.level = warn

logger.hsqldb.name = hsqldb.db
logger.hsqldb.level = warn

logger.hsqldbRepository.name = org.qortium.repository.hsqldb
logger.hsqldbRepository.level = debug

logger.jerseyInject.name = org.glassfish.jersey.internal.inject.Providers
logger.jerseyInject.level = off

logger.jerseyEOF.name = org.glassfish.jersey.server.internal
logger.jerseyEOF.level = off

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = warn

logger.jettyRS.name = org.eclipse.jetty.server.ResourceService
logger.jettyRS.level = error

logger.slf4j.name = org.slf4j
logger.slf4j.level = warn

logger.orgReflections.name = org.reflections.Reflections
logger.orgReflections.level = off
logger.sunReflections.name = sun.reflect.Reflection
logger.sunReflections.level = off

appender.console.type = Console
appender.console.name = stdout
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = error

appender.rolling.type = RollingFile
appender.rolling.name = FILE
appender.rolling.fileName = ${logDir}/qortium.log
appender.rolling.filePattern = ${logDir}/qortium.%d{dd-MMM}.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.rolling.policy.type = SizeBasedTriggeringPolicy
appender.rolling.policy.size = 10MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 7
