package org.qortium;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

public class MergeSettingsTests {

	private static final ObjectMapper MAPPER = new ObjectMapper();
	private static final TypeReference<LinkedHashMap<String, Object>> MAP_TYPE = new TypeReference<LinkedHashMap<String, Object>>() {};

	private Path tempDir;
	private Path templatePath;
	private Path snapshotPath;
	private Path settingsPath;

	@Before
	public void createTempFiles() throws IOException {
		tempDir = Files.createTempDirectory("qortium-merge-settings-test");
		templatePath = tempDir.resolve("settings-preview.json");
		snapshotPath = tempDir.resolve("settings-preview-local.template.json");
		settingsPath = tempDir.resolve("settings-preview-local.json");
	}

	@Test
	public void testFirstRunCreatesSettingsAndSnapshotFromTemplate() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertTrue(result.createdFromTemplate);
		assertTrue(result.preserved.isEmpty());
		assertEquals(readJson(templatePath), readJson(settingsPath));
		assertEquals(readJson(templatePath), readJson(snapshotPath));
	}

	@Test
	public void testLocalChangesAndAdditionsSurviveRestart() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");
		writeJson(snapshotPath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");
		writeJson(settingsPath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": true, \"apiKeyPath\": \"/runtime\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals("/runtime", merged.get("apiKeyPath"));
		assertEquals(24891, merged.get("apiPort"));
		assertTrue(result.preserved.contains("apiDocumentationEnabled"));
		assertTrue(result.preserved.contains("apiKeyPath"));
		assertFalse(result.preserved.contains("apiPort"));
	}

	@Test
	public void testUntouchedKeysFollowNewTemplate() throws Exception {
		writeJson(snapshotPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": false}");
		writeJson(settingsPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": true}");
		writeJson(templatePath, "{\"minPeerVersion\": \"1.1.0\", \"apiDocumentationEnabled\": false, \"newDefault\": 7}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals("1.1.0", merged.get("minPeerVersion"));
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals(7, merged.get("newDefault"));
		assertEquals(readJson(templatePath), readJson(snapshotPath));
	}

	@Test
	public void testLocalRemovalsStayRemoved() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"uPnPEnabled\": false}");
		writeJson(snapshotPath, "{\"apiPort\": 24891, \"uPnPEnabled\": false}");
		writeJson(settingsPath, "{\"apiPort\": 24891}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertFalse(merged.containsKey("uPnPEnabled"));
		assertTrue(result.removed.contains("uPnPEnabled"));
	}

	@Test
	public void testMigrationWithoutSnapshotKeepsChangesAndNewTemplateKeys() throws Exception {
		// Settings generated by the old clobbering launcher: no snapshot exists,
		// and the file lacks a key the new template introduced.
		writeJson(settingsPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": true}");
		writeJson(templatePath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": false, \"newDefault\": 7}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals(7, merged.get("newDefault"));
		assertEquals("1.0.0", merged.get("minPeerVersion"));
		assertTrue(result.removed.isEmpty());
		assertTrue(Files.exists(snapshotPath));
	}

	@Test
	public void testMigrationWithoutSnapshotAddsNewPublicApiPaths() throws Exception {
		writeJson(settingsPath, "{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\"]}");
		writeJson(templatePath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\", \"POST /transactions/process\"]}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue(
				"[\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\", \"POST /transactions/process\"]",
				Object.class), merged.get("publicApiPaths"));
		assertFalse(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testMigrationWithoutSnapshotKeepsCustomPublicApiPaths() throws Exception {
		writeJson(settingsPath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"GET /custom/*\"]}");
		writeJson(templatePath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\"]}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue(
				"[\"GET /admin/status\", \"GET /chat/*\", \"GET /custom/*\"]",
				Object.class), merged.get("publicApiPaths"));
		assertTrue(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testMigrationWithoutSnapshotEnablesArrrInUntouchedWalletMap() throws Exception {
		String oldWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":false}";
		String newWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":true}";
		writeJson(settingsPath, "{\"wallets\":" + oldWallets + "}");
		writeJson(templatePath, "{\"wallets\":" + newWallets + ","
				+ "\"pirateChainWalletUnified\":true,\"pirateChainWalletQdnSignature\":\"signature\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue(newWallets, Object.class), merged.get("wallets"));
		assertEquals(Boolean.TRUE, merged.get("pirateChainWalletUnified"));
		assertEquals("signature", merged.get("pirateChainWalletQdnSignature"));
		assertFalse(result.preserved.contains("wallets"));
	}

	@Test
	public void testMigrationWithoutSnapshotPreservesCustomizedWalletMap() throws Exception {
		String customWallets = "{\"BTC\":false,\"LTC\":true,\"ARRR\":false}";
		String newWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":true}";
		writeJson(settingsPath, "{\"wallets\":" + customWallets + "}");
		writeJson(templatePath, "{\"wallets\":" + newWallets + "}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(customWallets, Object.class), readJson(settingsPath).get("wallets"));
		assertTrue(result.preserved.contains("wallets"));
	}

	@Test
	public void testMigrationWithoutSnapshotPreservesWalletMapThatPredatesArrr() throws Exception {
		String oldWallets = "{\"BTC\":true,\"LTC\":true}";
		String newWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":true}";
		writeJson(settingsPath, "{\"wallets\":" + oldWallets + "}");
		writeJson(templatePath, "{\"wallets\":" + newWallets + "}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(oldWallets, Object.class), readJson(settingsPath).get("wallets"));
		assertTrue(result.preserved.contains("wallets"));
	}

	@Test
	public void testMigrationWithoutSnapshotKeepsAlreadyEnabledArrr() throws Exception {
		String enabledWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":true}";
		writeJson(settingsPath, "{\"wallets\":" + enabledWallets + "}");
		writeJson(templatePath, "{\"wallets\":" + enabledWallets + "}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(enabledWallets, Object.class), readJson(settingsPath).get("wallets"));
		assertFalse(result.preserved.contains("wallets"));
	}

	@Test
	public void testSnapshotUpgradeEnablesArrrUnlessWalletMapWasCustomized() throws Exception {
		String oldWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":false}";
		String newWallets = "{\"BTC\":true,\"LTC\":true,\"ARRR\":true}";
		writeJson(snapshotPath, "{\"wallets\":" + oldWallets + "}");
		writeJson(settingsPath, "{\"wallets\":" + oldWallets + "}");
		writeJson(templatePath, "{\"wallets\":" + newWallets + "}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(newWallets, Object.class), readJson(settingsPath).get("wallets"));

		writeJson(snapshotPath, "{\"wallets\":" + oldWallets + "}");
		writeJson(settingsPath, "{\"wallets\":{\"BTC\":false,\"LTC\":true,\"ARRR\":false}}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue("{\"BTC\":false,\"LTC\":true,\"ARRR\":false}", Object.class),
				readJson(settingsPath).get("wallets"));
		assertTrue(result.preserved.contains("wallets"));
	}

	@Test
	public void testUpgradeAddsPublicGroupBuildersToUntouchedPublicApiPaths() throws Exception {
		String oldPaths = "[\"GET /admin/status\",\"POST /chat/public/build\",\"POST /transactions/process\"]";
		String newPaths = "[\"GET /admin/status\",\"POST /chat/public/build\","
				+ "\"POST /groups/public/join\",\"POST /groups/public/leave\",\"POST /transactions/process\"]";
		writeJson(snapshotPath, "{\"publicApiPaths\":" + oldPaths + "}");
		writeJson(settingsPath, "{\"publicApiPaths\":" + oldPaths + "}");
		writeJson(templatePath, "{\"publicApiPaths\":" + newPaths + "}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(newPaths, Object.class), readJson(settingsPath).get("publicApiPaths"));
		assertFalse(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testUpgradePreservesExplicitPublicGroupBuilderRemoval() throws Exception {
		String oldPaths = "[\"GET /admin/status\",\"POST /chat/public/build\",\"POST /transactions/process\"]";
		String operatorPaths = "[\"GET /admin/status\",\"POST /transactions/process\"]";
		String newPaths = "[\"GET /admin/status\",\"POST /chat/public/build\","
				+ "\"POST /groups/public/join\",\"POST /groups/public/leave\",\"POST /transactions/process\"]";
		writeJson(snapshotPath, "{\"publicApiPaths\":" + oldPaths + "}");
		writeJson(settingsPath, "{\"publicApiPaths\":" + operatorPaths + "}");
		writeJson(templatePath, "{\"publicApiPaths\":" + newPaths + "}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(MAPPER.readValue(operatorPaths, Object.class), readJson(settingsPath).get("publicApiPaths"));
		assertTrue(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testMigrationAndRollbackKeepRetiredPeerClaimOrphaningDisabled() throws Exception {
		writeJson(templatePath, "{\"developmentPeerClaimOrphaningEnabled\":false}");
		writeJson(snapshotPath, "{\"apiPort\":24891}");
		writeJson(settingsPath, "{\"apiPort\":24891,\"recoveryWatchdogEnabled\":true,"
				+ "\"developmentPeerClaimOrphaningEnabled\":true}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.FALSE, merged.get("developmentPeerClaimOrphaningEnabled"));
		assertEquals(Boolean.FALSE, merged.get("recoveryWatchdogEnabled"));
		Map<String, Object> safeSnapshot = readJson(snapshotPath);
		assertFalse(safeSnapshot.containsKey("recoveryWatchdogEnabled"));
		assertFalse(safeSnapshot.containsKey("developmentPeerClaimOrphaningEnabled"));

		// Model a full rollback: the old template and merge behavior have no new-key special case.
		writeJson(templatePath, "{}");
		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> rolledBack = readJson(settingsPath);
		assertEquals(Boolean.FALSE, rolledBack.get("developmentPeerClaimOrphaningEnabled"));
		assertEquals(Boolean.FALSE, rolledBack.get("recoveryWatchdogEnabled"));
	}

	@Test
	public void testMigrationAndRollbackKeepHostedBootstrapRetired() throws Exception {
		writeJson(templatePath, "{\"bootstrap\":false,\"bootstrapHosts\":[]}");
		writeJson(snapshotPath, "{\"apiPort\":24891}");
		writeJson(settingsPath, "{\"apiPort\":24891,\"bootstrap\":true,"
				+ "\"bootstrapHosts\":[\"https://attacker.invalid\"]}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.FALSE, merged.get("bootstrap"));
		assertEquals(MAPPER.readValue("[]", Object.class), merged.get("bootstrapHosts"));
		assertFalse(result.preserved.contains("bootstrap"));
		assertFalse(result.preserved.contains("bootstrapHosts"));
		assertFalse(result.removed.contains("bootstrap"));
		assertFalse(result.removed.contains("bootstrapHosts"));
		Map<String, Object> safeSnapshot = readJson(snapshotPath);
		assertFalse(safeSnapshot.containsKey("bootstrap"));
		assertFalse(safeSnapshot.containsKey("bootstrapHosts"));

		// Model a full rollback to a template without the retirement marker. The generic merger must
		// preserve both safe runtime additions, including the empty host list required by old manual paths.
		writeJson(templatePath, "{}");
		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> rolledBack = readJson(settingsPath);
		assertEquals(Boolean.FALSE, rolledBack.get("bootstrap"));
		assertEquals(MAPPER.readValue("[]", Object.class), rolledBack.get("bootstrapHosts"));
	}

	@Test
	public void testCombinedRetirementSnapshotOmitsAllFourKeys() throws Exception {
		writeJson(templatePath, "{\"bootstrap\":false,\"bootstrapHosts\":[],"
				+ "\"recoveryWatchdogEnabled\":false,\"developmentPeerClaimOrphaningEnabled\":false}");
		writeJson(settingsPath, "{\"bootstrap\":true,\"bootstrapHosts\":[\"https://attacker.invalid\"],"
				+ "\"recoveryWatchdogEnabled\":true,\"developmentPeerClaimOrphaningEnabled\":true}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.FALSE, merged.get("bootstrap"));
		assertEquals(MAPPER.readValue("[]", Object.class), merged.get("bootstrapHosts"));
		assertEquals(Boolean.FALSE, merged.get("recoveryWatchdogEnabled"));
		assertEquals(Boolean.FALSE, merged.get("developmentPeerClaimOrphaningEnabled"));
		Map<String, Object> safeSnapshot = readJson(snapshotPath);
		assertFalse(safeSnapshot.containsKey("bootstrap"));
		assertFalse(safeSnapshot.containsKey("bootstrapHosts"));
		assertFalse(safeSnapshot.containsKey("recoveryWatchdogEnabled"));
		assertFalse(safeSnapshot.containsKey("developmentPeerClaimOrphaningEnabled"));
	}

	@Test
	public void testNestedValuesCompareByContent() throws Exception {
		writeJson(snapshotPath, "{\"initialPeers\": [\"1.2.3.4:24892\"], \"wallets\": {\"BTC\": false}}");
		writeJson(settingsPath, "{\"initialPeers\": [\"1.2.3.4:24892\"], \"wallets\": {\"BTC\": true}}");
		writeJson(templatePath, "{\"initialPeers\": [\"5.6.7.8:24892\"], \"wallets\": {\"BTC\": false}}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue("[\"5.6.7.8:24892\"]", Object.class), merged.get("initialPeers"));
		assertEquals(MAPPER.readValue("{\"BTC\": true}", Object.class), merged.get("wallets"));
	}

	// --- Superseded-value rule (P-CORE-59): pirateChainWalletQdnSignature ---

	private static final String CURRENT_PIRATE_PIN =
			"24hysb2o6HwXY6U7DmfdcZEpu4JtC5pF9WGftHhkeQPXeoNyatd8EfbUD6G2DptfhKKv9r7o865UEfXYFCCK2M6j";
	private static final String SUPERSEDED_PIRATE_PIN =
			"bEd5dM3wcbYWyG9hUHQQQsrYrYQ2rnYMDPahbqACpxCojjND5hwyUwiQQZNsTqRXu5awnsSurSwHnKkVeh24q7a";

	@Test
	public void testSupersededPinMigratesWithoutSnapshot() throws Exception {
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(CURRENT_PIRATE_PIN, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertTrue(result.migrated.contains("pirateChainWalletQdnSignature"));
		assertFalse(result.preserved.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinMigratesWithSnapshot() throws Exception {
		writeJson(snapshotPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(CURRENT_PIRATE_PIN, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertTrue(result.migrated.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleLeavesOperatorsThirdValueUntouched() throws Exception {
		String operatorPin = "operator-chosen-signature-value";
		writeJson(snapshotPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + operatorPin + "\"}");
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(operatorPin, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertFalse(result.migrated.contains("pirateChainWalletQdnSignature"));
		assertTrue(result.preserved.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleLeavesMissingKeyMissing() throws Exception {
		writeJson(snapshotPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{}");
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertFalse(readJson(settingsPath).containsKey("pirateChainWalletQdnSignature"));
		assertFalse(result.migrated.contains("pirateChainWalletQdnSignature"));
		assertTrue(result.removed.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleIsIdempotentOnSecondMerge() throws Exception {
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);
		assertEquals(CURRENT_PIRATE_PIN, readJson(settingsPath).get("pirateChainWalletQdnSignature"));

		MergeSettings.MergeResult second = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(CURRENT_PIRATE_PIN, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertFalse(second.migrated.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleDoesNotApplyWhenTemplateIsRollback() throws Exception {
		// The template itself has not advanced past the superseded value (e.g. a rollback to an
		// older release), so the local value -- even though it matches a listed superseded value --
		// must not be force-migrated forward.
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(SUPERSEDED_PIRATE_PIN, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertFalse(result.migrated.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleRequiresExactJsonType() throws Exception {
		// A local value that differs only in JSON type from a listed superseded value (here a JSON
		// number instead of the superseded string) must never be treated as a match.
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": 12345}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(12345, readJson(settingsPath).get("pirateChainWalletQdnSignature"));
		assertFalse(result.migrated.contains("pirateChainWalletQdnSignature"));
		assertTrue(result.preserved.contains("pirateChainWalletQdnSignature"));
	}

	@Test
	public void testSupersededPinRuleReportsOnlyTheKeyNeverTheValue() throws Exception {
		writeJson(templatePath, "{\"pirateChainWalletQdnSignature\": \"" + CURRENT_PIRATE_PIN + "\"}");
		writeJson(settingsPath, "{\"pirateChainWalletQdnSignature\": \"" + SUPERSEDED_PIRATE_PIN + "\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertEquals(List.of("pirateChainWalletQdnSignature"), result.migrated);
		// The stdout line built by main() is String.join(", ", result.migrated): confirm the list
		// itself carries only the key, so that line can never leak either pin value.
		String stdoutLine = String.format("Migrated superseded settings: %s", String.join(", ", result.migrated));
		assertFalse(stdoutLine.contains(CURRENT_PIRATE_PIN));
		assertFalse(stdoutLine.contains(SUPERSEDED_PIRATE_PIN));
	}

	@Test
	public void testRealV180ThreeFileFixtureMigratesToV123Pin() throws Exception {
		// A real v1.8.0-shipped settings-preview.json (with the v1.2.1 pin) used as both the
		// snapshot and the operator's local settings, merged against this worktree's current
		// template (with the v1.2.3 pin), must migrate the pin and leave every other key alone.
		Path shippedV180Fixture = Path.of("src/test/resources/mergesettings/settings-preview-v1.8.0.json");
		Files.copy(shippedV180Fixture, snapshotPath);
		Files.copy(shippedV180Fixture, settingsPath);
		Files.copy(Path.of("preview/settings-preview.json"), templatePath);

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(CURRENT_PIRATE_PIN, merged.get("pirateChainWalletQdnSignature"));
		assertTrue(result.migrated.contains("pirateChainWalletQdnSignature"));
		assertEquals(readJson(Path.of("preview/settings-preview.json")), merged);
	}

	@Test
	public void testInvalidSettingsJsonFailsWithoutTouchingFiles() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891}");
		Files.writeString(settingsPath, "{ not json", StandardCharsets.UTF_8);

		try {
			MergeSettings.merge(templatePath, snapshotPath, settingsPath);
			fail("Expected merge to reject invalid JSON");
		} catch (IOException e) {
			assertTrue(e.getMessage().contains(settingsPath.toString()));
		}

		assertEquals("{ not json", Files.readString(settingsPath, StandardCharsets.UTF_8));
		assertFalse(Files.exists(snapshotPath));
	}

	private static void writeJson(Path path, String json) throws IOException {
		Files.writeString(path, json, StandardCharsets.UTF_8);
	}

	private static Map<String, Object> readJson(Path path) throws IOException {
		return MAPPER.readValue(Files.readAllBytes(path), MAP_TYPE);
	}

}
