package org.qortium;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

public class MergeSettingsTests {

	private static final ObjectMapper MAPPER = new ObjectMapper();
	private static final TypeReference<LinkedHashMap<String, Object>> MAP_TYPE = new TypeReference<LinkedHashMap<String, Object>>() {};

	private Path tempDir;
	private Path templatePath;
	private Path snapshotPath;
	private Path settingsPath;

	@Before
	public void createTempFiles() throws IOException {
		tempDir = Files.createTempDirectory("qortium-merge-settings-test");
		templatePath = tempDir.resolve("settings-preview.json");
		snapshotPath = tempDir.resolve("settings-preview-local.template.json");
		settingsPath = tempDir.resolve("settings-preview-local.json");
	}

	@Test
	public void testFirstRunCreatesSettingsAndSnapshotFromTemplate() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		assertTrue(result.createdFromTemplate);
		assertTrue(result.preserved.isEmpty());
		assertEquals(readJson(templatePath), readJson(settingsPath));
		assertEquals(readJson(templatePath), readJson(snapshotPath));
	}

	@Test
	public void testLocalChangesAndAdditionsSurviveRestart() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");
		writeJson(snapshotPath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": false}");
		writeJson(settingsPath, "{\"apiPort\": 24891, \"apiDocumentationEnabled\": true, \"apiKeyPath\": \"/runtime\"}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals("/runtime", merged.get("apiKeyPath"));
		assertEquals(24891, merged.get("apiPort"));
		assertTrue(result.preserved.contains("apiDocumentationEnabled"));
		assertTrue(result.preserved.contains("apiKeyPath"));
		assertFalse(result.preserved.contains("apiPort"));
	}

	@Test
	public void testUntouchedKeysFollowNewTemplate() throws Exception {
		writeJson(snapshotPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": false}");
		writeJson(settingsPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": true}");
		writeJson(templatePath, "{\"minPeerVersion\": \"1.1.0\", \"apiDocumentationEnabled\": false, \"newDefault\": 7}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals("1.1.0", merged.get("minPeerVersion"));
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals(7, merged.get("newDefault"));
		assertEquals(readJson(templatePath), readJson(snapshotPath));
	}

	@Test
	public void testLocalRemovalsStayRemoved() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891, \"uPnPEnabled\": false}");
		writeJson(snapshotPath, "{\"apiPort\": 24891, \"uPnPEnabled\": false}");
		writeJson(settingsPath, "{\"apiPort\": 24891}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertFalse(merged.containsKey("uPnPEnabled"));
		assertTrue(result.removed.contains("uPnPEnabled"));
	}

	@Test
	public void testMigrationWithoutSnapshotKeepsChangesAndNewTemplateKeys() throws Exception {
		// Settings generated by the old clobbering launcher: no snapshot exists,
		// and the file lacks a key the new template introduced.
		writeJson(settingsPath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": true}");
		writeJson(templatePath, "{\"minPeerVersion\": \"1.0.0\", \"apiDocumentationEnabled\": false, \"newDefault\": 7}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(Boolean.TRUE, merged.get("apiDocumentationEnabled"));
		assertEquals(7, merged.get("newDefault"));
		assertEquals("1.0.0", merged.get("minPeerVersion"));
		assertTrue(result.removed.isEmpty());
		assertTrue(Files.exists(snapshotPath));
	}

	@Test
	public void testMigrationWithoutSnapshotAddsNewPublicApiPaths() throws Exception {
		writeJson(settingsPath, "{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\"]}");
		writeJson(templatePath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\", \"POST /transactions/process\"]}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue(
				"[\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\", \"POST /transactions/process\"]",
				Object.class), merged.get("publicApiPaths"));
		assertFalse(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testMigrationWithoutSnapshotKeepsCustomPublicApiPaths() throws Exception {
		writeJson(settingsPath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"GET /custom/*\"]}");
		writeJson(templatePath,
				"{\"publicApiPaths\": [\"GET /admin/status\", \"GET /chat/*\", \"POST /chat/public/build\"]}");

		MergeSettings.MergeResult result = MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue(
				"[\"GET /admin/status\", \"GET /chat/*\", \"GET /custom/*\"]",
				Object.class), merged.get("publicApiPaths"));
		assertTrue(result.preserved.contains("publicApiPaths"));
	}

	@Test
	public void testNestedValuesCompareByContent() throws Exception {
		writeJson(snapshotPath, "{\"initialPeers\": [\"1.2.3.4:24892\"], \"wallets\": {\"BTC\": false}}");
		writeJson(settingsPath, "{\"initialPeers\": [\"1.2.3.4:24892\"], \"wallets\": {\"BTC\": true}}");
		writeJson(templatePath, "{\"initialPeers\": [\"5.6.7.8:24892\"], \"wallets\": {\"BTC\": false}}");

		MergeSettings.merge(templatePath, snapshotPath, settingsPath);

		Map<String, Object> merged = readJson(settingsPath);
		assertEquals(MAPPER.readValue("[\"5.6.7.8:24892\"]", Object.class), merged.get("initialPeers"));
		assertEquals(MAPPER.readValue("{\"BTC\": true}", Object.class), merged.get("wallets"));
	}

	@Test
	public void testInvalidSettingsJsonFailsWithoutTouchingFiles() throws Exception {
		writeJson(templatePath, "{\"apiPort\": 24891}");
		Files.writeString(settingsPath, "{ not json", StandardCharsets.UTF_8);

		try {
			MergeSettings.merge(templatePath, snapshotPath, settingsPath);
			fail("Expected merge to reject invalid JSON");
		} catch (IOException e) {
			assertTrue(e.getMessage().contains(settingsPath.toString()));
		}

		assertEquals("{ not json", Files.readString(settingsPath, StandardCharsets.UTF_8));
		assertFalse(Files.exists(snapshotPath));
	}

	private static void writeJson(Path path, String json) throws IOException {
		Files.writeString(path, json, StandardCharsets.UTF_8);
	}

	private static Map<String, Object> readJson(Path path) throws IOException {
		return MAPPER.readValue(Files.readAllBytes(path), MAP_TYPE);
	}

}
