package org.qortal.crosschain;

import org.bitcoinj.core.Coin;
import org.bitcoinj.params.RegTestParams;
import org.bitcoinj.params.TestNet3Params;
import org.libdohj.params.DigibyteMainNetParams;
import org.qortal.crosschain.ElectrumX.Server;
import org.qortal.settings.Settings;

import java.util.Arrays;

public class Digibyte extends ConfiguredBitcoiny {

	public static final String CURRENCY_CODE = "DGB";

	private static final Coin DEFAULT_FEE_PER_KB = Coin.valueOf(100000); // 0.001 DGB per 1000 bytes

	private static final long MINIMUM_ORDER_AMOUNT = 1000000; // 0.01 DGB minimum order, to avoid dust errors

	// Temporary values until a dynamic fee system is written.
	private static final long MAINNET_FEE = 10000L;
	private static final long NON_MAINNET_FEE = 10000L; // enough for TESTNET3 and should be OK for REGTEST

	private static final BitcoinyChainConfig CONFIG = new BitcoinyChainConfig("Digibyte", CURRENCY_CODE,
			DEFAULT_FEE_PER_KB, MINIMUM_ORDER_AMOUNT, BitcoinyChainConfig.defaultElectrumXPorts());

	public enum DigibyteNet implements DelegatingBitcoinyNetwork {
		MAIN(StaticBitcoinyNetwork.mainnet(DigibyteMainNetParams::get,
				Arrays.asList(
					// Generated by tools/refresh-electrum-servers --update-builtins
					new Server("electrum1.cipig.net", Server.ConnectionType.SSL, 20059),
					new Server("electrum2.cipig.net", Server.ConnectionType.SSL, 20059),
					new Server("electrum3.cipig.net", Server.ConnectionType.SSL, 20059)
				),
				"7497ea1b465eb39f1c8f507bc877078fe016d6fcb6dfad3a64c98dcc6e1e8496", MAINNET_FEE)),
		TEST3(StaticBitcoinyNetwork.nonMainnet("TEST3", TestNet3Params::get,
				Arrays.asList(), // TODO: find testnet servers
				"308ea0711d5763be2995670dd9ca9872753561285a84da1d58be58acaa822252", MAINNET_FEE, NON_MAINNET_FEE)),
		REGTEST(StaticBitcoinyNetwork.nonMainnet("REGTEST", RegTestParams::get,
				Arrays.asList(
					new Server("localhost", Server.ConnectionType.SSL, 50002)
				),
				null, MAINNET_FEE, NON_MAINNET_FEE));

		private final BitcoinyNetwork delegate;

		DigibyteNet(BitcoinyNetwork delegate) {
			this.delegate = delegate;
		}

		@Override
		public BitcoinyNetwork getDelegate() {
			return this.delegate;
		}
	}

	private static Digibyte instance;

	private Digibyte(DigibyteNet digibyteNet) {
        super(CONFIG, digibyteNet);
	}

	public static synchronized Digibyte getInstance() {
		if (instance == null && Settings.getInstance().isWalletEnabled("DGB")) {
			instance = new Digibyte(Settings.getInstance().getDigibyteNet());
		}

		return instance;
	}

	// Getters & setters

	public static synchronized void resetForTesting() {
		instance = null;
	}

}
