package org.qortal.crosschain;

import java.util.Arrays;
import java.util.Collection;
import java.util.concurrent.atomic.AtomicLong;

import org.bitcoinj.core.Coin;
import org.bitcoinj.core.NetworkParameters;
import org.libdohj.params.DogecoinMainNetParams;
import org.libdohj.params.DogecoinTestNet3Params;
import org.qortal.crosschain.ElectrumX.Server;
import org.qortal.settings.Settings;

public class Dogecoin extends ConfiguredBitcoiny {

	public static final String CURRENCY_CODE = "DOGE";

	private static final Coin DEFAULT_FEE_PER_KB = Coin.valueOf(1000000); // 0.01 DOGE per 1000 bytes

	private static final long MINIMUM_ORDER_AMOUNT = 100000000L; // 1 DOGE minimum order. See recommendations:
	// https://github.com/dogecoin/dogecoin/blob/master/doc/fee-recommendation.md

	// Temporary values until a dynamic fee system is written.
	private static final long MAINNET_FEE = 100000L;
	private static final long NON_MAINNET_FEE = 10000L; // TODO: calibrate this

	private static final BitcoinyChainConfig CONFIG = new BitcoinyChainConfig("Dogecoin", CURRENCY_CODE,
			DEFAULT_FEE_PER_KB, MINIMUM_ORDER_AMOUNT, BitcoinyChainConfig.defaultElectrumXPorts());

	public enum DogecoinNet implements BitcoinyNetwork {
		MAIN {
			@Override
			public NetworkParameters getParams() {
				return DogecoinMainNetParams.get();
			}

			@Override
			public Collection<Server> getServers() {
				return Arrays.asList(
					// Generated by tools/refresh-electrum-servers --update-builtins
					new Server("doge.aftrek.org", Server.ConnectionType.SSL, 50002),
					new Server("dogecoin.stackwallet.com", Server.ConnectionType.SSL, 50022),
					new Server("electrum1.cipig.net", Server.ConnectionType.SSL, 20060),
					new Server("electrum2.cipig.net", Server.ConnectionType.SSL, 20060),
					new Server("electrum3.cipig.net", Server.ConnectionType.SSL, 20060)
				);
			}

			@Override
			public String getGenesisHash() {
				return "1a91e3dace36e2be3bf030a65679fe821aa1d6ef92e7c9902eb318182c355691";
			}

			@Override
			public long getP2shFee(Long timestamp) {
				return this.getFeeRequired();
			}
		},
		TEST3 {
			@Override
			public NetworkParameters getParams() {
				return DogecoinTestNet3Params.get();
			}

			@Override
			public Collection<Server> getServers() {
				return Arrays.asList(); // TODO: find testnet servers
			}

			@Override
			public String getGenesisHash() {
				return "4966625a4b2851d9fdee139e56211a0d88575f59ed816ff5e6a63deb4e3e29a0";
			}

			@Override
			public long getP2shFee(Long timestamp) {
				return NON_MAINNET_FEE;
			}
		},
		REGTEST {
			@Override
			public NetworkParameters getParams() {
				return null; // TODO: DogecoinRegTestParams.get();
			}

			@Override
			public Collection<Server> getServers() {
				return Arrays.asList(
					new Server("localhost", Server.ConnectionType.SSL, 50002)
				);
			}

			@Override
			public String getGenesisHash() {
				// This is unique to each regtest instance
				return null;
			}

			@Override
			public long getP2shFee(Long timestamp) {
				return NON_MAINNET_FEE;
			}
		};

		private AtomicLong feeRequired = new AtomicLong(MAINNET_FEE);

		public long getFeeRequired() {
			return feeRequired.get();
		}

		public void setFeeRequired(long feeRequired) {
			this.feeRequired.set(feeRequired);
		}

		public abstract NetworkParameters getParams();
		public abstract Collection<Server> getServers();
		public abstract String getGenesisHash();
		public abstract long getP2shFee(Long timestamp) throws ForeignBlockchainException;
	}

	private static Dogecoin instance;

	private Dogecoin(DogecoinNet dogecoinNet) {
		super(CONFIG, dogecoinNet);
	}

	public static synchronized Dogecoin getInstance() {
		if (instance == null && Settings.getInstance().isWalletEnabled("DOGE")) {
			instance = new Dogecoin(Settings.getInstance().getDogecoinNet());
		}

		return instance;
	}

	// Getters & setters

	public static synchronized void resetForTesting() {
		instance = null;
	}

}
