package org.qortal.crosschain;

import org.bitcoinj.core.Address;
import org.bitcoinj.core.Coin;
import org.bitcoinj.core.LegacyAddress;
import org.bitcoinj.core.NetworkParameters;
import org.bitcoinj.script.Script;
import org.libdohj.params.LitecoinMainNetParams;
import org.libdohj.params.LitecoinRegTestParams;
import org.libdohj.params.LitecoinTestNet3Params;
import org.qortal.crosschain.ElectrumX.Server;
import org.qortal.settings.Settings;

import java.util.Arrays;

public class Litecoin extends ConfiguredBitcoiny {

	public static final String CURRENCY_CODE = "LTC";

	private static final Coin DEFAULT_FEE_PER_KB = Coin.valueOf(10000); // 0.0001 LTC per 1000 bytes

	private static final long MINIMUM_ORDER_AMOUNT = 1000000; // 0.01 LTC minimum order, to avoid dust errors

	// Temporary values until a dynamic fee system is written.
	private static final long MAINNET_FEE = 1000L;
	private static final long NON_MAINNET_FEE = 1000L; // enough for TESTNET3 and should be OK for REGTEST

	public static final LitecoinMainNetParamsP2ShOverride MAIN_NET_PARAMS_P2SH_OVERRIDE = new LitecoinMainNetParamsP2ShOverride(50);

	private static final BitcoinyChainConfig CONFIG = new BitcoinyChainConfig("Litecoin", CURRENCY_CODE,
			DEFAULT_FEE_PER_KB, MINIMUM_ORDER_AMOUNT, BitcoinyChainConfig.defaultElectrumXPorts());

	public enum LitecoinNet implements DelegatingBitcoinyNetwork {
		MAIN(StaticBitcoinyNetwork.mainnet(LitecoinMainNetParams::get,
				Arrays.asList(
					// Generated by tools/refresh-electrum-servers --update-builtins
					new Server("188.166.208.106", Server.ConnectionType.SSL, 50002),
					new Server("209.38.53.75", Server.ConnectionType.SSL, 50002),
					new Server("24.199.78.132", Server.ConnectionType.SSL, 50002),
					new Server("5.161.216.180", Server.ConnectionType.SSL, 50002),
					new Server("5.78.97.174", Server.ConnectionType.SSL, 50002),
					new Server("88.119.167.62", Server.ConnectionType.SSL, 50012),
					new Server("backup.electrum-ltc.org", Server.ConnectionType.SSL, 443),
					new Server("backup.electrum-ltc.org", Server.ConnectionType.SSL, 50002),
					new Server("electrum-ltc.bysh.me", Server.ConnectionType.SSL, 50002),
					new Server("electrum-ltc.petrkr.net", Server.ConnectionType.SSL, 60002),
					new Server("electrum.jhoenicke.de", Server.ConnectionType.SSL, 50091),
					new Server("electrum.jochen-hoenicke.de", Server.ConnectionType.SSL, 50091),
					new Server("electrum.ltc.xurious.com", Server.ConnectionType.SSL, 50002),
					new Server("electrum.petrkr.net", Server.ConnectionType.SSL, 60002),
					new Server("electrum1.cipig.net", Server.ConnectionType.SSL, 20063),
					new Server("electrum2.cipig.net", Server.ConnectionType.SSL, 20063),
					new Server("electrum3.cipig.net", Server.ConnectionType.SSL, 20063),
					new Server("fallacy.fiatfaucet.com", Server.ConnectionType.SSL, 50002),
					new Server("l.fem.sh", Server.ConnectionType.SSL, 50002),
					new Server("litecoin.stackwallet.com", Server.ConnectionType.SSL, 20063),
					new Server("ltc-electrum.cakewallet.com", Server.ConnectionType.SSL, 50002),
					new Server("ltc.accessnodes.com", Server.ConnectionType.SSL, 60002),
					new Server("ltc.aftrek.org", Server.ConnectionType.SSL, 50002),
					new Server("ltc.rentonisk.com", Server.ConnectionType.SSL, 50002),
					new Server("ltc2.publicrypto.com", Server.ConnectionType.SSL, 60002)
				),
				"12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2", MAINNET_FEE)),
		TEST3(StaticBitcoinyNetwork.nonMainnet("TEST3", LitecoinTestNet3Params::get,
				Arrays.asList(
					// Generated by tools/refresh-electrum-servers --update-builtins
					new Server("electrum-ltc.bysh.me", Server.ConnectionType.SSL, 51002),
					new Server("electrum.ltc.xurious.com", Server.ConnectionType.SSL, 51002)
				),
				"4966625a4b2851d9fdee139e56211a0d88575f59ed816ff5e6a63deb4e3e29a0", MAINNET_FEE, NON_MAINNET_FEE)),
		REGTEST(StaticBitcoinyNetwork.nonMainnet("REGTEST", LitecoinRegTestParams::get,
				Arrays.asList(
					new Server("localhost", Server.ConnectionType.SSL, 50002)
				),
				null, MAINNET_FEE, NON_MAINNET_FEE));

		private final BitcoinyNetwork delegate;

		LitecoinNet(BitcoinyNetwork delegate) {
			this.delegate = delegate;
		}

		@Override
		public BitcoinyNetwork getDelegate() {
			return this.delegate;
		}
	}

	private static Litecoin instance;

	private Litecoin(LitecoinNet litecoinNet) {
		super(CONFIG, litecoinNet);
	}

	public static synchronized Litecoin getInstance() {
		if (instance == null && Settings.getInstance().isWalletEnabled("LTC")) {
			instance = new Litecoin(Settings.getInstance().getLitecoinNet());
		}

		return instance;
	}

	// Getters & setters

	public static synchronized void resetForTesting() {
		instance = null;
	}

	/**
	 * Is P2SH Address Current?
	 *
	 * Is the address conforming to the current p2sh standard, prefix 'M'?
	 *
	 * @param address the address
	 *
	 * @return true if conforms to the standard, otherwise false
	 */
	public boolean isCurrentP2ShAddress(String address) {
		try {
			Script.ScriptType addressType = Address.fromString(MAIN_NET_PARAMS_P2SH_OVERRIDE, address).getOutputScriptType();

			return addressType == Script.ScriptType.P2SH;
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), e);
			return false;
		}
	}

	@Override
	public String normalizeAddress(String address) {
		return isCurrentP2ShAddress(address) ? convertP2SHAddress(address, MAIN_NET_PARAMS_P2SH_OVERRIDE, this.params) : address;
	}

	/**
	 * Convert P2SH Address
	 *
	 * Convert p2sh address from one network standard to another.
	 *
	 * @param p2shAddress the p2sh address
	 * @param fromParams the existing standard
	 * @param toParams the desired standard
	 *
	 * @return the p2sh conforming to the desired standard
	 */
	private static String convertP2SHAddress(String p2shAddress, NetworkParameters fromParams, NetworkParameters toParams) {
		try {
			// decode the P2SH address
			Address address = LegacyAddress.fromBase58(fromParams, p2shAddress);
			byte[] hash = address.getHash();

			// create a new address with the target network parameters
			Address fromScriptHash = LegacyAddress.fromScriptHash(toParams, hash);

			// return the new address as a string
			return fromScriptHash.toString();
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), e);
			return null;
		}
	}
}
