package org.qortal.crosschain;

import org.bitcoinj.core.Coin;
import org.bitcoinj.params.RegTestParams;
import org.bitcoinj.params.TestNet3Params;
import org.libdohj.params.RavencoinMainNetParams;
import org.qortal.crosschain.ElectrumX.Server;
import org.qortal.settings.Settings;

import java.util.Arrays;

public class Ravencoin extends ConfiguredBitcoiny {

	public static final String CURRENCY_CODE = "RVN";

	private static final Coin DEFAULT_FEE_PER_KB = Coin.valueOf(1125000); // 0.01125 RVN per 1000 bytes

	private static final long MINIMUM_ORDER_AMOUNT = 1000000; // 0.01 RVN minimum order, to avoid dust errors

	// Temporary values until a dynamic fee system is written.
	private static final long MAINNET_FEE = 1000000L;
	private static final long NON_MAINNET_FEE = 1000000L; // enough for TESTNET3 and should be OK for REGTEST

	private static final BitcoinyChainConfig CONFIG = new BitcoinyChainConfig("Ravencoin", CURRENCY_CODE,
			DEFAULT_FEE_PER_KB, MINIMUM_ORDER_AMOUNT, BitcoinyChainConfig.defaultElectrumXPorts());

	public enum RavencoinNet implements DelegatingBitcoinyNetwork {
		MAIN(StaticBitcoinyNetwork.mainnet(RavencoinMainNetParams::get,
				Arrays.asList(
					// Generated by tools/refresh-electrum-servers --update-builtins
					new Server("162.19.153.65", Server.ConnectionType.SSL, 50002),
					new Server("electrum1.cipig.net", Server.ConnectionType.SSL, 20051),
					new Server("electrum2.cipig.net", Server.ConnectionType.SSL, 20051),
					new Server("electrum3.cipig.net", Server.ConnectionType.SSL, 20051),
					new Server("rvn-dashboard.com", Server.ConnectionType.SSL, 50002),
					new Server("rvn4lyfe.com", Server.ConnectionType.SSL, 50002)
				),
				"0000006b444bc2f2ffe627be9d9e7e7a0730000870ef6eb6da46c8eae389df90", MAINNET_FEE)),
		TEST3(StaticBitcoinyNetwork.nonMainnet("TEST3", TestNet3Params::get,
				Arrays.asList(), // TODO: find testnet servers
				"000000ecfc5e6324a079542221d00e10362bdc894d56500c414060eea8a3ad5a", MAINNET_FEE, NON_MAINNET_FEE)),
		REGTEST(StaticBitcoinyNetwork.nonMainnet("REGTEST", RegTestParams::get,
				Arrays.asList(
					new Server("localhost", Server.ConnectionType.SSL, 50002)
				),
				null, MAINNET_FEE, NON_MAINNET_FEE));

		private final BitcoinyNetwork delegate;

		RavencoinNet(BitcoinyNetwork delegate) {
			this.delegate = delegate;
		}

		@Override
		public BitcoinyNetwork getDelegate() {
			return this.delegate;
		}
	}

	private static Ravencoin instance;

	private Ravencoin(RavencoinNet ravencoinNet) {
		super(CONFIG, ravencoinNet);
	}

	public static synchronized Ravencoin getInstance() {
		if (instance == null && Settings.getInstance().isWalletEnabled("RVN")) {
			instance = new Ravencoin(Settings.getInstance().getRavencoinNet());
		}

		return instance;
	}

	// Getters & setters

	public static synchronized void resetForTesting() {
		instance = null;
	}

}
