#!/usr/bin/env bash

# default output post-processor
postproc=(cat)

# API defaults
port=14891
example_host=node.example.org

# called-as name
name="${0##*/}"

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

while [ -n "$*" ]; do
	case $1 in
		-p)
			shift
			postproc=(json_pp -f json -t json -json_opt "utf8,pretty")
			;;

		[Dd][Ee][Ll][Ee][Tt][Ee])
			shift
			method=(-X DELETE)
			;;

		-l)
			shift
			src=(--interface localhost)
			;;

		-t)
			shift
			testnet=true
			;;

		-j)
			shift
			content_type="Content-Type: application/json"
			;;

		*)
			break
			;;
	esac
done
	
port=${testnet:+24891}
port=${port:-14891}

if [ -z "$*" ]; then
	echo "usage: $name [-l] [-p] [-t] [DELETE] <url> [<post-data>]"
	echo "-l: use localhost as source address"
	echo "-p: pretty-print JSON output"
	echo "-t: use testnet port"
	echo "example (using localhost:${port}): $name -p blocks/last"
	echo "example: $name -p http://${example_host}:${port}/blocks/last"
	echo "example: BASE_URL=http://${example_host}:${port} $name -p blocks/last"
	echo "example: BASE_URL=${example_host} $name -p blocks/last"
	echo "example: $name -l DELETE peers/known"
	exit
fi

url=$1
shift

if [ -f "apikey.txt" ]; then
  apikey=$(cat "apikey.txt")
elif [ -f "${script_dir}/../apikey.txt" ]; then
  apikey=$(cat "${script_dir}/../apikey.txt")
elif [ -f "${HOME}/qortium/apikey.txt" ]; then
  apikey=$(cat "${HOME}/qortium/apikey.txt")
fi

if [ "${url:0:4}" != "http" ]; then
	base_url=${BASE_URL-localhost:${port}}

	if [ "${base_url:0:4}" != "http" ]; then
	        base_url="http://${base_url}"
	fi

	if [ -n "${base_url/#*:[0-9[0-9]*}" ]; then
	        base_url="${base_url%%/}:${port}"
	fi

	url="${base_url%%/}/${url#/}"
fi

if [ "$#" != 0 ]; then
	data=(--data)
fi

curl_args=(--silent --insecure --connect-timeout 5 -H "X-API-KEY: ${apikey}")
if [ -n "${content_type}" ]; then
	curl_args+=(--header "${content_type}")
fi

curl "${curl_args[@]}" "${method[@]}" "${src[@]}" --url "${url}" "${data[@]}" "$@" | "${postproc[@]}"
echo
