name: OSV-Scanner PR Scan

on:
  pull_request:
    branches: [ qortium-6.1.4 ]
  merge_group:
    branches: [ qortium-6.1.4 ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.8
    permissions:
      actions: read
      contents: read
      security-events: write
