name: PR testing

on:
  push:
    branches: [ master ]

jobs:
  mavenTesting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up the Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Load custom deps
      run: |
        mvn install -DskipTests=true --file pom.xml

    - name: Run all tests
      run: |
        mvn -B clean test jacoco:report jacoco:check -Pcoverage -DskipJUnitTests=false --file pom.xml

    - name: Log coverage percentage
      run: |
        if [ ! -f "target/site/jacoco/jacoco.csv" ]; then echo "No coverage information available"; exit 0; fi
        awk -F, 'NR > 1 { instruction_missed += $4; instruction_covered += $5; branch_missed += $6; branch_covered += $7; line_missed += $8; line_covered += $9 } END { instruction_total = instruction_missed + instruction_covered; branch_total = branch_missed + branch_covered; line_total = line_missed + line_covered; if (instruction_total > 0) printf "Instruction coverage: %.2f%% (%d/%d)\n", instruction_covered * 100 / instruction_total, instruction_covered, instruction_total; if (branch_total > 0) printf "Branch coverage: %.2f%% (%d/%d)\n", branch_covered * 100 / branch_total, branch_covered, branch_total; if (line_total > 0) printf "Line coverage: %.2f%% (%d/%d)\n", line_covered * 100 / line_total, line_covered, line_total; }' target/site/jacoco/jacoco.csv
        echo "Coverage report: target/site/jacoco/index.html"
